In [1]:
%run SectionManager.ipynb
%run Constant.ipynb

print('Hello')

symbol='SZ#002022'

sm = SectionManager(symbol,level_day,30,60)

sm.build_file_path()

Hello

'/Users/xinwang/stock/data/original_sections/Day/Day_30_60_sections_V0.8_SZ#002022.txt'

In [2]:
sm.get_all_cross_sections()

start to analyse Day level SZ#002022 all cross sections...

,symbol,s_date,e_date,s_price,e_price,ampl,ma_per,periods,boll,price_incre_per,ma_short_direction,ma_mid_direction,break_mid_ma_price_incre,boll99,enter_to_highest_increase_per,s_datetime,e_datetime
1,SZ#002022,2004-12-22,2004-12-24,-0.68,-0.72,10.53,-3.28,3,False,-5.88,Down,Down,-10.29,True,-0.00,2004-12-22,2004-12-24
2,SZ#002022,2005-03-18,2005-05-11,-0.73,-0.99,44.66,-1.33,33,False,-35.62,Up,Down,-9.59,False,-21.92,2005-03-18,2005-05-11
3,SZ#002022,2005-07-19,2006-07-27,-0.92,1.31,322.58,255.91,222,False,242.39,Up,Down,245.65,False,-325.00,2005-07-19,2006-07-27
4,SZ#002022,2006-09-22,2007-12-04,1.72,9.87,773.24,722.73,288,True,473.84,Up,Up,-10.47,True,620.93,2006-09-22,2007-12-04
5,SZ#002022,2007-12-28,2008-03-27,13.04,12.10,43.09,28.26,58,True,-7.21,Up,Up,-10.28,True,27.84,2007-12-28,2008-03-27
6,SZ#002022,2008-05-29,2008-07-04,13.23,13.24,31.39,-4.49,25,False,0.08,Up,Down,-5.90,False,7.56,2008-05-29,2008-07-04
7,SZ#002022,2008-08-07,2008-08-29,12.95,10.34,32.62,-5.55,17,False,-20.15,Up,Down,-3.40,False,1.08,2008-08-07,2008-08-29
8,SZ#002022,2008-12-05,2009-03-04,11.42,11.27,29.81,19.94,57,True,-1.31,Up,Up,-1.14,True,18.21,2008-12-05,2009-03-04
9,SZ#002022,2009-05-08,2009-08-19,11.73,10.66,52.45,9.84,71,False,-9.12,Up,Unknown,7.59,False,38.02,2009-05-08,2009-08-19
10,SZ#002022,2009-10-09,2010-01-06,13.66,15.69,56.68,24.67,63,True,14.86,Up,Down,7.91,True,45.10,2009-10-09,2010-01-06
11,SZ#002022,2010-02-11,2010-05-10,16.39,14.92,45.92,11.24,56,False,-8.97,Up,Down,-9.33,True,25.44,2010-02-11,2010-05-10
12,SZ#002022,2010-08-27,2011-01-13,14.16,15.10,66.05,20.66,91,False,6.64,Up,Down,-0.35,False,52.33,2010-08-27,2011-01-13
13,SZ#002022,2011-03-22,2011-04-19,14.78,14.28,6.54,-3.05,19,False,-3.38,Up,Down,0.47,False,2.57,2011-03-22,2011-04-19
14,SZ#002022,2011-07-28,2011-08-29,12.65,12.10,28.76,-2.89,23,True,-4.35,Up,Down,-6.09,False,2.29,2011-07-28,2011-08-29
15,SZ#002022,2011-11-28,2011-12-29,11.95,8.50,56.53,-3.54,24,True,-28.87,Up,Up,-10.21,True,7.28,2011-11-28,2011-12-29
16,SZ#002022,2012-03-08,2012-04-27,9.79,9.47,22.67,0.54,33,True,-3.27,Up,Down,-11.95,False,6.13,2012-03-08,2012-04-27
17,SZ#002022,2012-05-24,2012-10-09,9.51,10.11,27.81,9.08,93,False,6.31,Up,Unknown,-1.79,True,20.82,2012-05-24,2012-10-09
18,SZ#002022,2012-07-10,2012-10-09,9.67,10.11,24.89,8.52,61,False,4.55,Up,Up,4.96,True,18.82,2012-07-10,2012-10-09
19,SZ#002022,2012-07-17,2012-10-09,9.79,10.11,24.89,7.84,56,True,3.27,Up,Up,3.68,True,17.36,2012-07-17,2012-10-09
20,SZ#002022,2013-01-22,2013-07-15,9.96,15.61,74.21,55.63,112,True,56.73,Up,Up,33.13,True,65.46,2013-01-22,2013-07-15
21,SZ#002022,2013-08-05,2013-09-23,17.15,15.18,20.49,1.43,34,True,-11.49,Up,Up,-11.66,True,1.17,2013-08-05,2013-09-23
22,SZ#002022,2013-12-11,2014-04-30,15.69,21.15,60.41,48.19,69,True,34.80,Up,Up,35.63,True,58.06,2013-12-11,2014-04-30
23,SZ#002022,2014-07-01,2014-11-07,23.16,24.71,25.75,19.89,88,True,6.69,Up,Up,7.38,True,21.24,2014-07-01,2014-11-07
24,SZ#002022,2015-02-12,2015-07-29,25.72,33.08,153.92,80.17,104,True,28.62,Up,Up,18.90,True,146.81,2015-02-12,2015-07-29
25,SZ#002022,2015-11-10,2016-01-12,29.07,20.34,66.07,11.06,45,True,-30.03,Up,Down,-13.93,False,12.32,2015-11-10,2016-01-12
26,SZ#002022,2016-04-19,2016-05-26,20.75,18.03,22.00,-3.16,27,True,-13.11,Up,Up,-7.76,False,1.01,2016-04-19,2016-05-26
27,SZ#002022,2016-07-04,2016-08-24,21.34,20.65,15.58,3.26,38,True,-3.23,Up,Up,-8.76,True,2.91,2016-07-04,2016-08-24
28,SZ#002022,2016-09-08,2016-11-21,24.13,22.79,15.42,6.44,46,True,-5.55,Up,Up,-9.99,True,0.50,2016-09-08,2016-11-21
29,SZ#002022,2017-03-10,2017-04-27,20.24,19.25,11.81,0.05,33,True,-4.89,Up,Down,-2.52,False,3.80,2017-03-10,2017-04-27
30,SZ#002022,2017-09-12,2017-11-08,17.89,16.35,13.18,1.24,37,True,-8.61,Up,Up,-9.39,True,2.24,2017-09-12,2017-11-08
31,SZ#002022,2018-04-09,2018-06-22,14.19,11.68,38.60,3.14,52,True,-17.69,Up,Up,-3.38,True,10.08,2018-04-09,2018-06-22
32,SZ#002022,2018-12-12,2018-12-27,9.95,9.35,9.07,-2.79,12,False,-6.03,Up,Down,0.40,False,1.51,2018-12-12,2018-12-27