In [5]:
%run SectionManager.ipynb
%run Constant.ipynb

print('Hello')

symbol='SZ#002022'

sm = SectionManager(symbol,level_day,30,60)

sm.build_file_path()

Hello

'/Users/xinwang/stock/data/original_sections/Day/Day_30_60_sections_V0.1.1_SZ#002022.txt'

In [6]:
sm.get_all_cross_sections()

build SZ#002022 sections
start to analyse Day level SZ#002022 all cross sections...

,symbol,d_s_date,d_e_date,d_s_price,d_e_price,ampl,ma_per,periods,boll,price_incre_per,...,boll99,enter_to_highest_increase_per,highest_date,highest_price,lowest_date,lowest_price,mfe,mae,d_s_datetime,d_e_datetime
1,SZ#002022,2004-12-22,2004-12-24,-0.68,-0.72,10.53,-3.28,3,False,-5.88,...,True,-0.00,2004-12-22,-0.68,2004-12-24,-0.76,0.000000,1.355932,2004-12-22,2004-12-24
2,SZ#002022,2005-03-18,2005-05-11,-0.73,-0.99,44.66,-1.33,33,False,-35.62,...,False,-21.92,2005-04-15,-0.57,2005-05-10,-1.03,3.200000,6.000000,2005-03-18,2005-05-11
3,SZ#002022,2005-07-19,2006-07-27,-0.92,1.31,322.58,255.91,222,False,242.39,...,False,-325.00,2006-05-22,2.07,2005-07-19,-0.93,65.000000,0.217391,2005-07-19,2006-07-27
4,SZ#002022,2006-09-22,2007-12-04,1.72,9.87,773.24,722.73,288,True,473.84,...,True,620.93,2007-11-01,12.40,2006-11-14,1.42,95.357143,2.678571,2006-09-22,2007-12-04
5,SZ#002022,2007-12-28,2008-03-27,13.04,12.10,43.09,28.26,58,True,-7.21,...,True,27.84,2008-01-24,16.67,2008-03-18,11.65,5.734597,2.195893,2007-12-28,2008-03-27
6,SZ#002022,2008-05-29,2008-07-04,13.23,13.24,31.39,-4.49,25,False,0.08,...,False,7.56,2008-06-04,14.23,2008-06-24,10.83,1.379310,3.310345,2008-05-29,2008-07-04
7,SZ#002022,2008-08-07,2008-08-29,12.95,10.34,32.62,-5.55,17,False,-20.15,...,False,1.08,2008-08-08,13.09,2008-08-28,9.87,0.280000,6.160000,2008-08-07,2008-08-29
8,SZ#002022,2008-12-05,2009-03-04,11.42,11.27,29.81,19.94,57,True,-1.31,...,True,18.21,2009-02-11,13.50,2009-03-03,10.40,3.816514,1.871560,2008-12-05,2009-03-04
9,SZ#002022,2009-05-08,2009-08-19,11.73,10.66,52.45,9.84,71,False,-9.12,...,False,38.02,2009-06-19,16.19,2009-08-19,10.62,6.676647,1.661677,2009-05-08,2009-08-19
10,SZ#002022,2009-10-09,2010-01-06,13.66,15.69,56.68,24.67,63,True,14.86,...,True,45.10,2009-11-20,19.82,2009-10-09,12.65,7.359618,1.206691,2009-10-09,2010-01-06
11,SZ#002022,2010-02-11,2010-05-10,16.39,14.92,45.92,11.24,56,False,-8.97,...,True,25.44,2010-04-21,20.56,2010-05-10,14.09,5.346154,2.948718,2010-02-11,2010-05-10
12,SZ#002022,2010-08-27,2011-01-13,14.16,15.10,66.05,20.66,91,False,6.64,...,False,52.33,2010-11-30,21.57,2010-10-18,12.99,12.247934,1.933884,2010-08-27,2011-01-13
13,SZ#002022,2011-03-22,2011-04-19,14.78,14.28,6.54,-3.05,19,False,-3.38,...,False,2.57,2011-03-24,15.16,2011-03-31,14.23,0.848214,1.227679,2011-03-22,2011-04-19
14,SZ#002022,2011-07-28,2011-08-29,12.65,12.10,28.76,-2.89,23,True,-4.35,...,False,2.29,2011-07-29,12.94,2011-08-09,10.05,0.679157,6.088993,2011-07-28,2011-08-29
15,SZ#002022,2011-11-28,2011-12-29,11.95,8.50,56.53,-3.54,24,True,-28.87,...,True,7.28,2011-12-01,12.82,2011-12-28,8.19,2.066508,8.931116,2011-11-28,2011-12-29
16,SZ#002022,2012-03-08,2012-04-27,9.79,9.47,22.67,0.54,33,True,-3.27,...,False,6.13,2012-03-14,10.39,2012-04-10,8.47,2.120141,4.664311,2012-03-08,2012-04-27
17,SZ#002022,2012-05-24,2012-10-09,9.51,10.11,27.81,9.08,93,False,6.31,...,True,20.82,2012-08-15,11.49,2012-05-28,8.99,7.500000,1.969697,2012-05-24,2012-10-09
18,SZ#002022,2012-07-10,2012-10-09,9.67,10.11,24.89,8.52,61,False,4.55,...,True,18.82,2012-08-15,11.49,2012-09-26,9.20,5.498489,1.419940,2012-07-10,2012-10-09
19,SZ#002022,2012-07-17,2012-10-09,9.79,10.11,24.89,7.84,56,True,3.27,...,True,17.36,2012-08-15,11.49,2012-09-26,9.20,4.292929,1.489899,2012-07-17,2012-10-09
20,SZ#002022,2013-01-22,2013-07-15,9.96,15.61,74.21,55.63,112,True,56.73,...,True,65.46,2013-05-31,16.48,2013-01-24,9.46,17.912088,1.373626,2013-01-22,2013-07-15
21,SZ#002022,2013-08-05,2013-09-23,17.15,15.18,20.49,1.43,34,True,-11.49,...,True,1.17,2013-08-12,17.35,2013-08-30,14.40,0.270270,3.716216,2013-08-05,2013-09-23
22,SZ#002022,2013-12-11,2014-04-30,15.69,21.15,60.41,48.19,69,True,34.80,...,True,58.06,2014-03-19,24.80,2013-12-17,15.46,17.124060,0.432331,2013-12-11,2014-04-30
23,SZ#002022,2014-07-01,2014-11-07,23.16,24.71,25.75,19.89,88,True,6.69,...,True,21.24,2014-09-15,28.08,2014-07-01,22.33,7.161572,1.208151,2014-07-01,2014-11-07
24,SZ#002022,2015-02-12,2015-07-29,25.72,33.08,153.92,80.17,104,True,28.62,...,True,146.81,2015-06-15,63.48,2015-02-12,25.00,37.949749,0.723618,2015-02-12,2015-07-29
25,SZ#002022,2015-11-10,2016-01-12,29.07,20.34,66.07,11.06,45,True,-30.03,...,False,12.32,2015-12-22,32.65,2016-01-12,19.66,2.409152,6.332436,2015-11-10,2016-01-12
26,SZ#002022,2016-04-19,2016-05-26,20.75,18.03,22.00,-3.16,27,True,-13.11,...,False,1.01,2016-04-19,20.96,2016-05-09,17.18,0.260870,4.434783,2016-04-19,2016-05-26
27,SZ#002022,2016-07-04,2016-08-24,21.34,20.65,15.58,3.26,38,True,-3.23,...,True,2.91,2016-07-13,21.96,2016-08-01,19.00,0.813648,3.070866,2016-07-04,2016-08-24
28,SZ#002022,2016-09-08,2016-11-21,24.13,22.79,15.42,6.44,46,True,-5.55,...,True,0.50,2016-09-08,24.25,2016-11-09,21.01,0.110092,2.862385,2016-09-08,2016-11-21
29,SZ#002022,2017-03-10,2017-04-27,20.24,19.25,11.81,0.05,33,True,-4.89,...,False,3.80,2017-03-22,21.01,2017-04-24,18.79,2.383901,4.489164,2017-03-10,2017-04-27
30,SZ#002022,2017-09-12,2017-11-08,17.89,16.35,13.18,1.24,37,True,-8.61,...,True,2.24,2017-10-10,18.29,2017-10-31,16.16,1.294498,5.598706,2017-09-12,2017-11-08
31,SZ#002022,2018-04-09,2018-06-22,14.19,11.68,38.60,3.14,52,True,-17.69,...,True,10.08,2018-05-16,15.62,2018-06-19,11.27,2.217054,4.527132,2018-04-09,2018-06-22
32,SZ#002022,2018-12-12,2018-12-27,9.95,9.35,9.07,-2.79,12,False,-6.03,...,False,1.51,2018-12-13,10.10,2018-12-25,9.26,0.447761,2.059701,2018-12-12,2018-12-27