In [28]:
%run BreakSectionManager.ipynb

symbol = 'SZ#002161'
sectionManager = BreakSectionManager(symbol, level_day, 5, 10)
sections = sectionManager.analyse_all_break_sections()
sections

start to analyse Day level SZ#002161 all break sections...
2007-11-21 highest_price 3.87 cur_price:4.0
2007-11-27 lowest_price 3.41 cur_price:3.39
2007-11-21 section ['SZ#002161', '2007-11-21', '2007-11-27', 4.0, 3.39]
end_date 2007-11-27
2007-12-11 highest_price 3.63 cur_price:3.67
2008-01-17 lowest_price 4.41 cur_price:4.37
2007-12-11 section ['SZ#002161', '2007-12-11', '2008-01-17', 3.67, 4.37]
end_date 2008-01-17
2008-02-15 highest_price 5.12 cur_price:5.15
2008-02-25 lowest_price 5.17 cur_price:5.07
2008-02-15 section ['SZ#002161', '2008-02-15', '2008-02-25', 5.15, 5.07]
end_date 2008-02-25
2008-03-04 highest_price 5.44 cur_price:5.49
2008-03-18 lowest_price 5.25 cur_price:4.97
2008-03-04 section ['SZ#002161', '2008-03-04', '2008-03-18', 5.49, 4.97]
end_date 2008-03-18
2008-03-24 highest_price 6.13 cur_price:6.24
2008-04-01 lowest_price 5.92 cur_price:5.78
2008-03-24 section ['SZ#002161', '2008-03-24', '2008-04-01', 6.24, 5.78]
end_date 2008-04-01
2008-05-05 highest_price 5.98 cur_price:6.2
2008-05-13 lowest_price 5.68 cur_price:5.5
2008-05-05 section ['SZ#002161', '2008-05-05', '2008-05-13', 6.2, 5.5]
end_date 2008-05-13
2008-05-23 highest_price 6.02 cur_price:6.13
2008-05-30 lowest_price 5.68 cur_price:5.61
2008-05-23 section ['SZ#002161', '2008-05-23', '2008-05-30', 6.13, 5.61]
end_date 2008-05-30
2008-06-05 highest_price 6.22 cur_price:6.37
2008-06-13 lowest_price 6.26 cur_price:6.1
2008-06-05 section ['SZ#002161', '2008-06-05', '2008-06-13', 6.37, 6.1]
end_date 2008-06-13
2008-11-06 highest_price 2.5 cur_price:2.52
2008-12-12 lowest_price 3.54 cur_price:3.43
2008-11-06 section ['SZ#002161', '2008-11-06', '2008-12-12', 2.52, 3.43]
end_date 2008-12-12
2009-02-02 highest_price 3.79 cur_price:3.8
2009-02-17 lowest_price 3.92 cur_price:3.87
2009-02-02 section ['SZ#002161', '2009-02-02', '2009-02-17', 3.8, 3.87]
end_date 2009-02-17
2009-03-12 highest_price 3.63 cur_price:3.88
2009-05-11 lowest_price 5.5 cur_price:5.37
2009-03-12 section ['SZ#002161', '2009-03-12', '2009-05-11', 3.88, 5.37]
end_date 2009-05-11
2009-06-02 highest_price 5.86 cur_price:6.31
2009-06-15 lowest_price 6.12 cur_price:6.1
2009-06-02 section ['SZ#002161', '2009-06-02', '2009-06-15', 6.31, 6.1]
end_date 2009-06-15
2009-07-09 highest_price 6.32 cur_price:6.44
2009-07-24 lowest_price 7.0 cur_price:6.93
2009-07-09 section ['SZ#002161', '2009-07-09', '2009-07-24', 6.44, 6.93]
end_date 2009-07-24
2009-08-26 highest_price 6.33 cur_price:6.47
2009-08-31 lowest_price 5.85 cur_price:5.53
2009-08-26 section ['SZ#002161', '2009-08-26', '2009-08-31', 6.47, 5.53]
end_date 2009-08-31
2009-09-14 highest_price 6.08 cur_price:6.41
2009-09-24 lowest_price 8.59 cur_price:8.56
2009-09-14 section ['SZ#002161', '2009-09-14', '2009-09-24', 6.41, 8.56]
end_date 2009-09-24
2009-11-19 highest_price 9.54 cur_price:9.59
2009-11-24 lowest_price 9.09 cur_price:9.01
2009-11-19 section ['SZ#002161', '2009-11-19', '2009-11-24', 9.59, 9.01]
end_date 2009-11-24
2010-01-05 highest_price 8.63 cur_price:8.71
2010-01-07 lowest_price 8.19 cur_price:8.16
2010-01-05 section ['SZ#002161', '2010-01-05', '2010-01-07', 8.71, 8.16]
end_date 2010-01-07
2010-01-12 highest_price 8.84 cur_price:9.1
2010-01-20 lowest_price 8.93 cur_price:8.82
2010-01-12 section ['SZ#002161', '2010-01-12', '2010-01-20', 9.1, 8.82]
end_date 2010-01-20
2010-02-24 highest_price 8.04 cur_price:8.05
2010-04-15 lowest_price 9.16 cur_price:8.96
2010-02-24 section ['SZ#002161', '2010-02-24', '2010-04-15', 8.05, 8.96]
end_date 2010-04-15
2010-06-02 highest_price 7.16 cur_price:7.24
2010-06-17 lowest_price 7.06 cur_price:7.03
2010-06-02 section ['SZ#002161', '2010-06-02', '2010-06-17', 7.24, 7.03]
end_date 2010-06-17
2010-07-22 highest_price 6.46 cur_price:6.54
2010-09-16 lowest_price 8.67 cur_price:8.25
2010-07-22 section ['SZ#002161', '2010-07-22', '2010-09-16', 6.54, 8.25]
end_date 2010-09-16
2010-10-11 highest_price 9.1 cur_price:9.16
2010-11-17 lowest_price 10.63 cur_price:9.9
2010-10-11 section ['SZ#002161', '2010-10-11', '2010-11-17', 9.16, 9.9]
end_date 2010-11-17
2010-12-10 highest_price 12.68 cur_price:13.21
2010-12-23 lowest_price 12.93 cur_price:12.61
2010-12-10 section ['SZ#002161', '2010-12-10', '2010-12-23', 13.21, 12.61]
end_date 2010-12-23
2011-02-14 highest_price 11.97 cur_price:12.11
2011-02-22 lowest_price 12.11 cur_price:12.09
2011-02-14 section ['SZ#002161', '2011-02-14', '2011-02-22', 12.11, 12.09]
end_date 2011-02-22
2011-03-16 highest_price 12.52 cur_price:12.79
2011-03-21 lowest_price 11.98 cur_price:11.94
2011-03-16 section ['SZ#002161', '2011-03-16', '2011-03-21', 12.79, 11.94]
end_date 2011-03-21
2011-05-13 highest_price 10.59 cur_price:10.63
2011-05-20 lowest_price 10.63 cur_price:10.6
2011-05-13 section ['SZ#002161', '2011-05-13', '2011-05-20', 10.63, 10.6]
end_date 2011-05-20
2011-06-30 highest_price 10.47 cur_price:11.09
2011-07-21 lowest_price 11.24 cur_price:11.16
2011-06-30 section ['SZ#002161', '2011-06-30', '2011-07-21', 11.09, 11.16]
end_date 2011-07-21
2011-11-03 highest_price 9.17 cur_price:9.29
2011-11-18 lowest_price 9.59 cur_price:9.5
2011-11-03 section ['SZ#002161', '2011-11-03', '2011-11-18', 9.29, 9.5]
end_date 2011-11-18
2012-02-03 highest_price 8.36 cur_price:8.5
2012-02-28 lowest_price 9.56 cur_price:9.55
2012-02-03 section ['SZ#002161', '2012-02-03', '2012-02-28', 8.5, 9.55]
end_date 2012-02-28
2012-03-12 highest_price 9.74 cur_price:9.81
2012-03-14 lowest_price 9.38 cur_price:9.2
2012-03-12 section ['SZ#002161', '2012-03-12', '2012-03-14', 9.81, 9.2]
end_date 2012-03-14
2012-04-24 highest_price 9.79 cur_price:9.89
2012-04-27 lowest_price 9.22 cur_price:9.12
2012-04-24 section ['SZ#002161', '2012-04-24', '2012-04-27', 9.89, 9.12]
end_date 2012-04-27
2012-05-31 highest_price 8.81 cur_price:8.92
2012-06-04 lowest_price 8.53 cur_price:8.43
2012-05-31 section ['SZ#002161', '2012-05-31', '2012-06-04', 8.92, 8.43]
end_date 2012-06-04
2012-08-03 highest_price 7.77 cur_price:7.95
2012-08-13 lowest_price 8.08 cur_price:8.04
2012-08-03 section ['SZ#002161', '2012-08-03', '2012-08-13', 7.95, 8.04]
end_date 2012-08-13
2012-08-21 highest_price 8.42 cur_price:8.44
2012-08-27 lowest_price 8.1 cur_price:7.81
2012-08-21 section ['SZ#002161', '2012-08-21', '2012-08-27', 8.44, 7.81]
end_date 2012-08-27
2012-09-07 highest_price 8.16 cur_price:8.3
2012-09-13 lowest_price 8.06 cur_price:8.03
2012-09-07 section ['SZ#002161', '2012-09-07', '2012-09-13', 8.3, 8.03]
end_date 2012-09-13
2012-10-19 highest_price 7.94 cur_price:7.98
2012-10-24 lowest_price 7.8 cur_price:7.72
2012-10-19 section ['SZ#002161', '2012-10-19', '2012-10-24', 7.98, 7.72]
end_date 2012-10-24
2012-12-14 highest_price 5.77 cur_price:5.91
2013-01-22 lowest_price 6.92 cur_price:6.61
2012-12-14 section ['SZ#002161', '2012-12-14', '2013-01-22', 5.91, 6.61]
end_date 2013-01-22
2013-01-24 highest_price 7.36 cur_price:7.77
2013-02-04 lowest_price 7.43 cur_price:7.33
2013-01-24 section ['SZ#002161', '2013-01-24', '2013-02-04', 7.77, 7.33]
end_date 2013-02-04
2013-02-18 highest_price 8.12 cur_price:8.26
2013-02-22 lowest_price 7.93 cur_price:7.8
2013-02-18 section ['SZ#002161', '2013-02-18', '2013-02-22', 8.26, 7.8]
end_date 2013-02-22
2013-03-07 highest_price 8.53 cur_price:8.57
2013-03-12 lowest_price 8.17 cur_price:7.78
2013-03-07 section ['SZ#002161', '2013-03-07', '2013-03-12', 8.57, 7.78]
end_date 2013-03-12
2013-05-09 highest_price 8.03 cur_price:8.06
2013-06-04 lowest_price 9.43 cur_price:9.36
2013-05-09 section ['SZ#002161', '2013-05-09', '2013-06-04', 8.06, 9.36]
end_date 2013-06-04
2013-07-15 highest_price 8.76 cur_price:9.05
2013-08-08 lowest_price 9.73 cur_price:9.71
2013-07-15 section ['SZ#002161', '2013-07-15', '2013-08-08', 9.05, 9.71]
end_date 2013-08-08
2013-08-21 highest_price 9.93 cur_price:10.09
2013-08-28 lowest_price 9.65 cur_price:9.53
2013-08-21 section ['SZ#002161', '2013-08-21', '2013-08-28', 10.09, 9.53]
end_date 2013-08-28
2013-09-23 highest_price 9.55 cur_price:9.56
2013-09-26 lowest_price 9.12 cur_price:9.02
2013-09-23 section ['SZ#002161', '2013-09-23', '2013-09-26', 9.56, 9.02]
end_date 2013-09-26
2013-10-08 highest_price 9.71 cur_price:9.72
2013-10-24 lowest_price 9.75 cur_price:9.69
2013-10-08 section ['SZ#002161', '2013-10-08', '2013-10-24', 9.72, 9.69]
end_date 2013-10-24

2014-01-24 highest_price 7.63 cur_price:7.77
2014-03-10 lowest_price 8.11 cur_price:7.57
2014-01-24 section ['SZ#002161', '2014-01-24', '2014-03-10', 7.77, 7.57]
end_date 2014-03-10
2014-05-13 highest_price 6.82 cur_price:6.85
2014-06-04 lowest_price 6.57 cur_price:6.43
2014-05-13 section ['SZ#002161', '2014-05-13', '2014-06-04', 6.85, 6.43]
end_date 2014-06-04
2014-06-20 highest_price 6.84 cur_price:6.89
2014-07-07 lowest_price 7.36 cur_price:7.35
2014-06-20 section ['SZ#002161', '2014-06-20', '2014-07-07', 6.89, 7.35]
end_date 2014-07-07
2014-07-15 highest_price 7.7 cur_price:7.73
2014-07-24 lowest_price 7.27 cur_price:7.12
2014-07-15 section ['SZ#002161', '2014-07-15', '2014-07-24', 7.73, 7.12]
end_date 2014-07-24
2014-08-04 highest_price 7.53 cur_price:7.56
2014-08-14 lowest_price 7.49 cur_price:7.48
2014-08-04 section ['SZ#002161', '2014-08-04', '2014-08-14', 7.56, 7.48]
end_date 2014-08-14
2014-08-19 highest_price 7.73 cur_price:7.8
2014-08-26 lowest_price 7.54 cur_price:7.39
2014-08-19 section ['SZ#002161', '2014-08-19', '2014-08-26', 7.8, 7.39]
end_date 2014-08-26
2014-09-05 highest_price 7.78 cur_price:7.81
2014-09-16 lowest_price 7.8 cur_price:7.65
2014-09-05 section ['SZ#002161', '2014-09-05', '2014-09-16', 7.81, 7.65]
end_date 2014-09-16
2014-09-18 highest_price 8.12 cur_price:8.2
2014-10-17 lowest_price 8.35 cur_price:8.23
2014-09-18 section ['SZ#002161', '2014-09-18', '2014-10-17', 8.2, 8.23]
end_date 2014-10-17
2014-11-19 highest_price 8.96 cur_price:8.99
2014-12-05 lowest_price 8.5 cur_price:8.49
2014-11-19 section ['SZ#002161', '2014-11-19', '2014-12-05', 8.99, 8.49]
end_date 2014-12-05
2015-01-06 highest_price 8.27 cur_price:8.31
2015-01-12 lowest_price 7.99 cur_price:7.78
2015-01-06 section ['SZ#002161', '2015-01-06', '2015-01-12', 8.31, 7.78]
end_date 2015-01-12
2015-01-21 highest_price 8.31 cur_price:8.37
2015-02-09 lowest_price 9.47 cur_price:9.45
2015-01-21 section ['SZ#002161', '2015-01-21', '2015-02-09', 8.37, 9.45]
end_date 2015-02-09
2015-02-11 highest_price 10.25 cur_price:10.28
2015-06-08 lowest_price 27.88 cur_price:27.62
2015-02-11 section ['SZ#002161', '2015-02-11', '2015-06-08', 10.28, 27.62]
end_date 2015-06-08
2015-09-11 highest_price 12.51 cur_price:13.18
2015-09-15 lowest_price 10.7 cur_price:10.67
2015-09-11 section ['SZ#002161', '2015-09-11', '2015-09-15', 13.18, 10.67]
end_date 2015-09-15
2015-10-12 highest_price 13.58 cur_price:14.38
2015-10-21 lowest_price 14.38 cur_price:14.28
2015-10-12 section ['SZ#002161', '2015-10-12', '2015-10-21', 14.38, 14.28]
end_date 2015-10-21
2015-10-27 highest_price 16.65 cur_price:16.92
2015-11-02 lowest_price 14.98 cur_price:14.61
2015-10-27 section ['SZ#002161', '2015-10-27', '2015-11-02', 16.92, 14.61]
end_date 2015-11-02
2015-11-09 highest_price 16.93 cur_price:17.36
2015-11-27 lowest_price 23.79 cur_price:22.36
2015-11-09 section ['SZ#002161', '2015-11-09', '2015-11-27', 17.36, 22.36]
end_date 2015-11-27
2016-02-16 highest_price 13.78 cur_price:14.12
2016-02-25 lowest_price 13.98 cur_price:13.3
2016-02-16 section ['SZ#002161', '2016-02-16', '2016-02-25', 14.12, 13.3]
end_date 2016-02-25
2016-03-14 highest_price 12.88 cur_price:13.49
2016-03-29 lowest_price 16.28 cur_price:15.33
2016-03-14 section ['SZ#002161', '2016-03-14', '2016-03-29', 13.49, 15.33]
end_date 2016-03-29
2016-05-26 highest_price 13.65 cur_price:13.76
2016-06-13 lowest_price 14.14 cur_price:13.17
2016-05-26 section ['SZ#002161', '2016-05-26', '2016-06-13', 13.76, 13.17]
end_date 2016-06-13
2016-06-23 highest_price 14.74 cur_price:14.91
2016-07-18 lowest_price 14.29 cur_price:14.24
2016-06-23 section ['SZ#002161', '2016-06-23', '2016-07-18', 14.91, 14.24]
end_date 2016-07-18
2016-08-18 highest_price 13.57 cur_price:13.79
2016-08-22 lowest_price 13.37 cur_price:13.29
2016-08-18 section ['SZ#002161', '2016-08-18', '2016-08-22', 13.79, 13.29]
end_date 2016-08-22
2016-10-10 highest_price 13.33 cur_price:13.39
2016-10-17 lowest_price 13.38 cur_price:13.21
2016-10-10 section ['SZ#002161', '2016-10-10', '2016-10-17', 13.39, 13.21]
end_date 2016-10-17
2017-02-08 highest_price 10.49 cur_price:10.51
2017-02-17 lowest_price 10.44 cur_price:10.35
2017-02-08 section ['SZ#002161', '2017-02-08', '2017-02-17', 10.51, 10.35]
end_date 2017-02-17
2017-04-06 highest_price 10.62 cur_price:11.2
2017-04-14 lowest_price 10.71 cur_price:10.5
2017-04-06 section ['SZ#002161', '2017-04-06', '2017-04-14', 11.2, 10.5]
end_date 2017-04-14
2017-06-15 highest_price 8.03 cur_price:8.19
2017-06-22 lowest_price 8.04 cur_price:7.98
2017-06-15 section ['SZ#002161', '2017-06-15', '2017-06-22', 8.19, 7.98]
end_date 2017-06-22
2017-07-04 highest_price 8.26 cur_price:8.98
2017-08-11 lowest_price 11.7 cur_price:11.5
2017-07-04 section ['SZ#002161', '2017-07-04', '2017-08-11', 8.98, 11.5]
end_date 2017-08-11
2017-08-18 highest_price 12.68 cur_price:12.81
2017-09-01 lowest_price 12.05 cur_price:12.0
2017-08-18 section ['SZ#002161', '2017-08-18', '2017-09-01', 12.81, 12.0]
end_date 2017-09-01
2017-09-08 highest_price 12.94 cur_price:13.62
2017-09-15 lowest_price 12.9 cur_price:12.04
2017-09-08 section ['SZ#002161', '2017-09-08', '2017-09-15', 13.62, 12.04]
end_date 2017-09-15
2017-12-13 highest_price 9.23 cur_price:9.45
2017-12-20 lowest_price 8.99 cur_price:8.9
2017-12-13 section ['SZ#002161', '2017-12-13', '2017-12-20', 9.45, 8.9]
end_date 2017-12-20
2018-05-30 highest_price 8.82 cur_price:9.12
2018-06-28 lowest_price 9.75 cur_price:9.56
2018-05-30 section ['SZ#002161', '2018-05-30', '2018-06-28', 9.12, 9.56]
end_date 2018-06-28
2018-09-21 highest_price 7.11 cur_price:7.12
2018-10-08 lowest_price 7.02 cur_price:6.83
2018-09-21 section ['SZ#002161', '2018-09-21', '2018-10-08', 7.12, 6.83]
end_date 2018-10-08
2018-11-06 highest_price 6.16 cur_price:6.17
2018-11-23 lowest_price 6.52 cur_price:6.07
2018-11-06 section ['SZ#002161', '2018-11-06', '2018-11-23', 6.17, 6.07]
end_date 2018-11-23
2019-01-15 highest_price 5.93 cur_price:6.26
2019-01-22 lowest_price 5.86 cur_price:5.84
2019-01-15 section ['SZ#002161', '2019-01-15', '2019-01-22', 6.26, 5.84]
end_date 2019-01-22
2019-02-18 highest_price 5.75 cur_price:5.89
2019-02-18 section ['SZ#002161', '2019-02-18', None, 5.89, None]

       symbol      s_date      e_date  s_price  e_price s_datetime e_datetime
1   SZ#002161  2007-11-21  2007-11-27     4.00     3.39 2007-11-21 2007-11-27
2   SZ#002161  2007-12-11  2008-01-17     3.67     4.37 2007-12-11 2008-01-17
3   SZ#002161  2008-02-15  2008-02-25     5.15     5.07 2008-02-15 2008-02-25
4   SZ#002161  2008-03-04  2008-03-18     5.49     4.97 2008-03-04 2008-03-18
5   SZ#002161  2008-03-24  2008-04-01     6.24     5.78 2008-03-24 2008-04-01
6   SZ#002161  2008-05-05  2008-05-13     6.20     5.50 2008-05-05 2008-05-13
7   SZ#002161  2008-05-23  2008-05-30     6.13     5.61 2008-05-23 2008-05-30
8   SZ#002161  2008-06-05  2008-06-13     6.37     6.10 2008-06-05 2008-06-13
9   SZ#002161  2008-11-06  2008-12-12     2.52     3.43 2008-11-06 2008-12-12
10  SZ#002161  2009-02-02  2009-02-17     3.80     3.87 2009-02-02 2009-02-17
11  SZ#002161  2009-03-12  2009-05-11     3.88     5.37 2009-03-12 2009-05-11
12  SZ#002161  2009-06-02  2009-06-15     6.31     6.10 2009-06-02 2009-06-15
13  SZ#002161  2009-07-09  2009-07-24     6.44     6.93 2009-07-09 2009-07-24
14  SZ#002161  2009-08-26  2009-08-31     6.47     5.53 2009-08-26 2009-08-31
15  SZ#002161  2009-09-14  2009-09-24     6.41     8.56 2009-09-14 2009-09-24
16  SZ#002161  2009-11-19  2009-11-24     9.59     9.01 2009-11-19 2009-11-24
17  SZ#002161  2010-01-05  2010-01-07     8.71     8.16 2010-01-05 2010-01-07
18  SZ#002161  2010-01-12  2010-01-20     9.10     8.82 2010-01-12 2010-01-20
19  SZ#002161  2010-02-24  2010-04-15     8.05     8.96 2010-02-24 2010-04-15
20  SZ#002161  2010-06-02  2010-06-17     7.24     7.03 2010-06-02 2010-06-17
21  SZ#002161  2010-07-22  2010-09-16     6.54     8.25 2010-07-22 2010-09-16
22  SZ#002161  2010-10-11  2010-11-17     9.16     9.90 2010-10-11 2010-11-17
23  SZ#002161  2010-12-10  2010-12-23    13.21    12.61 2010-12-10 2010-12-23
24  SZ#002161  2011-02-14  2011-02-22    12.11    12.09 2011-02-14 2011-02-22
25  SZ#002161  2011-03-16  2011-03-21    12.79    11.94 2011-03-16 2011-03-21
26  SZ#002161  2011-05-13  2011-05-20    10.63    10.60 2011-05-13 2011-05-20
27  SZ#002161  2011-06-30  2011-07-21    11.09    11.16 2011-06-30 2011-07-21
28  SZ#002161  2011-11-03  2011-11-18     9.29     9.50 2011-11-03 2011-11-18
29  SZ#002161  2012-02-03  2012-02-28     8.50     9.55 2012-02-03 2012-02-28
30  SZ#002161  2012-03-12  2012-03-14     9.81     9.20 2012-03-12 2012-03-14
..        ...         ...         ...      ...      ...        ...        ...
49  SZ#002161  2014-07-15  2014-07-24     7.73     7.12 2014-07-15 2014-07-24
50  SZ#002161  2014-08-04  2014-08-14     7.56     7.48 2014-08-04 2014-08-14
51  SZ#002161  2014-08-19  2014-08-26     7.80     7.39 2014-08-19 2014-08-26
52  SZ#002161  2014-09-05  2014-09-16     7.81     7.65 2014-09-05 2014-09-16
53  SZ#002161  2014-09-18  2014-10-17     8.20     8.23 2014-09-18 2014-10-17
54  SZ#002161  2014-11-19  2014-12-05     8.99     8.49 2014-11-19 2014-12-05
55  SZ#002161  2015-01-06  2015-01-12     8.31     7.78 2015-01-06 2015-01-12
56  SZ#002161  2015-01-21  2015-02-09     8.37     9.45 2015-01-21 2015-02-09
57  SZ#002161  2015-02-11  2015-06-08    10.28    27.62 2015-02-11 2015-06-08
58  SZ#002161  2015-09-11  2015-09-15    13.18    10.67 2015-09-11 2015-09-15
59  SZ#002161  2015-10-12  2015-10-21    14.38    14.28 2015-10-12 2015-10-21
60  SZ#002161  2015-10-27  2015-11-02    16.92    14.61 2015-10-27 2015-11-02
61  SZ#002161  2015-11-09  2015-11-27    17.36    22.36 2015-11-09 2015-11-27
62  SZ#002161  2016-02-16  2016-02-25    14.12    13.30 2016-02-16 2016-02-25
63  SZ#002161  2016-03-14  2016-03-29    13.49    15.33 2016-03-14 2016-03-29
64  SZ#002161  2016-05-26  2016-06-13    13.76    13.17 2016-05-26 2016-06-13
65  SZ#002161  2016-06-23  2016-07-18    14.91    14.24 2016-06-23 2016-07-18
66  SZ#002161  2016-08-18  2016-08-22    13.79    13.29 2016-08-18 2016-08-22
67  SZ#002161  2016-10-10  2016-10-17    13.39    13.21 2016-10-10 2016-10-17
68  SZ#002161  2017-02-08  2017-02-17    10.51    10.35 2017-02-08 2017-02-17
69  SZ#002161  2017-04-06  2017-04-14    11.20    10.50 2017-04-06 2017-04-14
70  SZ#002161  2017-06-15  2017-06-22     8.19     7.98 2017-06-15 2017-06-22
71  SZ#002161  2017-07-04  2017-08-11     8.98    11.50 2017-07-04 2017-08-11
72  SZ#002161  2017-08-18  2017-09-01    12.81    12.00 2017-08-18 2017-09-01
73  SZ#002161  2017-09-08  2017-09-15    13.62    12.04 2017-09-08 2017-09-15
74  SZ#002161  2017-12-13  2017-12-20     9.45     8.90 2017-12-13 2017-12-20
75  SZ#002161  2018-05-30  2018-06-28     9.12     9.56 2018-05-30 2018-06-28
76  SZ#002161  2018-09-21  2018-10-08     7.12     6.83 2018-09-21 2018-10-08
77  SZ#002161  2018-11-06  2018-11-23     6.17     6.07 2018-11-06 2018-11-23
78  SZ#002161  2019-01-15  2019-01-22     6.26     5.84 2019-01-15 2019-01-22

[78 rows x 7 columns]